logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: data-app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml

server:
  port: 8081
